[package]
name = "rustnightlyhash"
version = "0.1.0"
authors = ["Michał Krasnoborski <mkrdln@gmail.com>"]

[dependencies]
serde_json = "*"
hyper = "*"
time = "*"
docopt = "*"
docopt_macros = "*"
rustc-serialize = "*"
